// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArSqD3NEKHjIxD2oGagSx61A31bOzCR9k',
    appId: '1:314252762954:web:c583faa3f539adfc996bb3',
    messagingSenderId: '314252762954',
    projectId: 'wemos-app-fb01f',
    authDomain: 'wemos-app-fb01f.firebaseapp.com',
    databaseURL: 'https://wemos-app-fb01f-default-rtdb.firebaseio.com',
    storageBucket: 'wemos-app-fb01f.firebasestorage.app',
    measurementId: 'G-L1WR5EGSWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNXbujuHXfXFaNNKq-6fFallwOg9ZmBR4',
    appId: '1:314252762954:android:bf398c90bf4e9f68996bb3',
    messagingSenderId: '314252762954',
    projectId: 'wemos-app-fb01f',
    databaseURL: 'https://wemos-app-fb01f-default-rtdb.firebaseio.com',
    storageBucket: 'wemos-app-fb01f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmABKB5rhAj9RSz878snYYggBQLGzdhBo',
    appId: '1:314252762954:ios:891835aed0089e70996bb3',
    messagingSenderId: '314252762954',
    projectId: 'wemos-app-fb01f',
    databaseURL: 'https://wemos-app-fb01f-default-rtdb.firebaseio.com',
    storageBucket: 'wemos-app-fb01f.firebasestorage.app',
    iosBundleId: 'com.example.wemosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmABKB5rhAj9RSz878snYYggBQLGzdhBo',
    appId: '1:314252762954:ios:891835aed0089e70996bb3',
    messagingSenderId: '314252762954',
    projectId: 'wemos-app-fb01f',
    storageBucket: 'wemos-app-fb01f.firebasestorage.app',
    iosBundleId: 'com.example.wemosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArSqD3NEKHjIxD2oGagSx61A31bOzCR9k',
    appId: '1:314252762954:web:d509fb7d80c60f80996bb3',
    messagingSenderId: '314252762954',
    projectId: 'wemos-app-fb01f',
    authDomain: 'wemos-app-fb01f.firebaseapp.com',
    storageBucket: 'wemos-app-fb01f.firebasestorage.app',
    measurementId: 'G-EWJKSM7523',
  );

}